/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  images: {
    /**
     * Template covers are placeholder SVGs generated by our own route
     * (app/api/placeholder/[surface]/[seed]) — a pure function of the URL, not
     * a user upload. next/image refuses SVGs by default (the optimizer returns
     * 400), which left every template card blank.
     *
     * Allowing SVG is safe here because the source is first-party and the
     * strict CSP below neutralises the one real risk — a script embedded in an
     * SVG — by forbidding scripts and sandboxing the rendered image. This is
     * the pairing Next documents for trusted SVGs.
     */
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
};

export default nextConfig;
