/**
 * Catalog seed content — Ph2.md §1.
 *
 * Plain data, no Prisma import, so it can be asserted against in unit tests
 * without a database. prisma/seed.ts turns it into rows.
 *
 * The copy is placeholder content written to be plausible for a Cebu print
 * shop, not final marketing text. It exists so the marketplace can be built and
 * reviewed before ML Printing supplies real templates.
 */

export interface SeedCategory {
  slug: string;
  name: string;
  description: string;
  sortOrder: number;
}

/**
 * The event types from Ph2.md §1, plus "Custom".
 *
 * Rows, not code — adding "Reunion" later is an INSERT. This array only seeds
 * the initial set; nothing reads it at runtime.
 */
export const CATEGORIES: SeedCategory[] = [
  {
    slug: "engagement",
    name: "Engagement",
    description: "Proposals and engagement parties.",
    sortOrder: 5,
  },
  {
    slug: "wedding",
    name: "Wedding",
    description: "Ceremonies and receptions.",
    sortOrder: 10,
  },
  {
    slug: "birthday",
    name: "Birthday",
    description: "Every age, every style.",
    sortOrder: 20,
  },
  {
    slug: "christening",
    name: "Christening",
    description: "Baptisms and dedications.",
    sortOrder: 30,
  },
  {
    slug: "baby-shower",
    name: "Baby Shower",
    description: "Welcoming a little one on the way.",
    sortOrder: 35,
  },
  {
    slug: "debut",
    name: "Debut",
    description: "The Filipino 18th birthday.",
    sortOrder: 40,
  },
  {
    slug: "anniversary",
    name: "Anniversary",
    description: "Milestones worth marking.",
    sortOrder: 50,
  },
  {
    slug: "graduation",
    name: "Graduation",
    description: "Commencements and recognitions.",
    sortOrder: 60,
  },
  {
    slug: "corporate",
    name: "Corporate",
    description: "Launches, galas, and company events.",
    sortOrder: 70,
  },
  {
    slug: "reunion",
    name: "Reunion",
    description: "Families, classes, and old friends.",
    sortOrder: 80,
  },
  {
    slug: "family",
    name: "Family Celebration",
    description: "Noche Buena, handaan, and everything in between.",
    sortOrder: 82,
  },
  {
    slug: "fiesta",
    name: "Fiesta",
    description: "Barangay and town fiestas.",
    sortOrder: 84,
  },
  {
    slug: "religious",
    name: "Religious",
    description: "Masses, blessings, and church occasions.",
    sortOrder: 86,
  },
  {
    slug: "community",
    name: "Community Event",
    description: "Barangay programmes and civic gatherings.",
    sortOrder: 88,
  },
  {
    slug: "funeral",
    name: "Memorial",
    description: "Funeral and memorial notices.",
    sortOrder: 90,
  },
  {
    slug: "custom",
    name: "Custom",
    description: "Anything that does not fit a box.",
    sortOrder: 999,
  },
];

export interface SeedCollection {
  slug: string;
  name: string;
  description: string;
  /** Month-day window, e.g. "12-01". Null means always active. */
  activeFrom: string | null;
  activeTo: string | null;
}

/** Ph2.md §1 — Seasonal. The window is why collections exist at all. */
export const COLLECTIONS: SeedCollection[] = [
  {
    slug: "christmas",
    name: "Christmas",
    description: "Templates for the Philippine Christmas season.",
    activeFrom: "09-01",
    activeTo: "12-31",
  },
  {
    slug: "summer",
    name: "Summer",
    description: "Bright templates for the dry season.",
    activeFrom: "03-01",
    activeTo: "05-31",
  },
];

export interface SeedTemplate {
  slug: string;
  name: string;
  category: string;
  shortDescription: string;
  description: string;
  designer: string;
  tags: string[];
  colors: string[];
  styles: string[];
  features: string[];
  /**
   * Cover composition — the `style` half of lib/placeholder-art.ts.
   *
   * Not a filter facet, and deliberately not the same thing as `styles`. The
   * category fixes the palette and the wording of a cover; this fixes its
   * shape, which is what stops fifty templates reading as one template fifty
   * times. Keep it in step with `ArtStyle`: a value that module does not know
   * silently falls back to the category default.
   */
  style:
    | "classic"
    | "floral"
    | "gold-foil"
    | "luxury"
    | "kids"
    | "fairy"
    | "portrait"
    | "minimal";
  orientation: "PORTRAIT" | "LANDSCAPE" | "SQUARE";
  tier: "FREE" | "PREMIUM";
  printCompatible: boolean;
  websiteCompatible: boolean;
  isFeatured: boolean;
  /** Days before seed time. Drives "New" and the newest sort. */
  publishedDaysAgo: number;
  /** Seeds the Most Popular sort so the ordering is observable. */
  useCount: number;
  collections?: string[];
}

/**
 * Seed templates — FDG-ML-DEP-STD-015 §4.
 *
 * Fifty published, plus one unpublished draft. Sized and spread deliberately:
 * several pages at the default 12 per page (so pagination is exercised), a mix
 * of tiers, orientations, colours, styles, and publication dates (so every
 * filter and sort in §4/§5 returns a non-trivial result), and a few that are
 * print-only or website-only (so §7's compatibility flags are not uniformly
 * true).
 *
 * Two spreads matter and are easy to break by adding templates carelessly:
 * every category carries at least one published template, and every cover
 * composition appears often enough that no single one defines the catalogue.
 */
export const TEMPLATES: SeedTemplate[] = [
  {
    slug: "ivory-lace",
    name: "Ivory Lace",
    category: "wedding",
    shortDescription: "Classic lace borders on warm ivory.",
    description:
      "A traditional wedding suite built around a fine lace border and a serif wordmark. Reads formal without tipping into fussy, and holds up in both a printed suite and a single-page website.",
    designer: "ML Printing Studio",
    tags: ["lace", "classic", "formal", "traditional"],
    colors: ["ivory", "gold"],
    styles: ["classic", "elegant"],
    features: ["rsvp", "gallery", "map", "timeline"],
    style: "floral",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 120,
    useCount: 184,
  },
  {
    slug: "blush-botanical",
    name: "Blush Botanical",
    category: "wedding",
    shortDescription: "Soft botanicals in blush and sage.",
    description:
      "Hand-drawn botanicals frame the page in blush and sage. The lightest of the wedding suites, and the most forgiving of long names and long guest lists.",
    designer: "ML Printing Studio",
    tags: ["botanical", "floral", "garden", "soft"],
    colors: ["blush", "sage"],
    styles: ["modern", "minimal"],
    features: ["rsvp", "gallery", "map"],
    style: "floral",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 14,
    useCount: 97,
  },
  {
    slug: "midnight-gold",
    name: "Midnight Gold",
    category: "wedding",
    shortDescription: "Deep navy with gold foil accents.",
    description:
      "Built for evening receptions. Navy ground with gold accents intended for foil stock — the print version is the point, and the website version follows it rather than the other way round.",
    designer: "Cebu Type Co.",
    tags: ["foil", "evening", "formal", "luxe"],
    colors: ["navy", "gold"],
    styles: ["elegant", "classic"],
    features: ["rsvp", "timeline"],
    style: "gold-foil",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 200,
    useCount: 143,
  },
  {
    slug: "coastal-linen",
    name: "Coastal Linen",
    category: "wedding",
    shortDescription: "Barefoot beach wedding, understated.",
    description:
      "A linen-textured layout for beach ceremonies, with generous margins and a wide landscape crop for panoramic photography.",
    designer: "Cebu Type Co.",
    tags: ["beach", "coastal", "relaxed", "summer"],
    colors: ["sand", "seafoam"],
    styles: ["minimal", "rustic"],
    features: ["rsvp", "gallery", "map"],
    style: "portrait",
    orientation: "LANDSCAPE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 45,
    useCount: 61,
    collections: ["summer"],
  },
  {
    slug: "gilded-vow",
    name: "Gilded Vow",
    category: "wedding",
    shortDescription: "Gold foil on ivory for a church wedding.",
    description:
      "A formal wedding suite set in gold on ivory, with the type panelled so foil stock has something to catch against. Written for a church ceremony followed by a sit-down reception.",
    designer: "ML Printing Studio",
    tags: ["foil", "formal", "church", "traditional"],
    colors: ["gold", "ivory"],
    styles: ["elegant", "classic"],
    features: ["rsvp", "gallery", "map", "timeline"],
    style: "gold-foil",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 18,
    useCount: 131,
  },
  {
    slug: "sampaguita",
    name: "Sampaguita",
    category: "wedding",
    shortDescription: "Sampaguita garlands for a daytime wedding.",
    description:
      "Strands of sampaguita drawn as a ring around the couple's names. Suits a morning church wedding and a garden reception, and holds its detail printed in two colours.",
    designer: "Cebu Type Co.",
    tags: ["sampaguita", "floral", "garland", "filipino"],
    colors: ["white", "sage"],
    styles: ["classic", "soft"],
    features: ["rsvp", "gallery", "map"],
    style: "floral",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 9,
    useCount: 78,
  },
  {
    slug: "two-of-us",
    name: "Two of Us",
    category: "wedding",
    shortDescription: "Illustrated couple under an arch.",
    description:
      "An illustrated portrait of the couple beneath a ceremony arch, drawn rather than photographed. For couples with no engagement shoot yet who do not want to wait for one.",
    designer: "Isla Studio",
    tags: ["illustrated", "couple", "portrait", "arch"],
    colors: ["blush", "cream"],
    styles: ["modern", "soft"],
    features: ["rsvp", "gallery", "map", "timeline"],
    style: "portrait",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 34,
    useCount: 66,
  },
  {
    slug: "capiz-window",
    name: "Capiz Window",
    category: "wedding",
    shortDescription: "Capiz shell panes and warm gold.",
    description:
      "A heritage wedding suite laid out on the grid of a capiz shell window, with a gold fan above the names. Made for ancestral-house receptions and long guest lists.",
    designer: "Bantayan Press",
    tags: ["capiz", "heritage", "filipino", "luxe"],
    colors: ["cream", "gold"],
    styles: ["elegant", "classic"],
    features: ["rsvp", "gallery", "map", "timeline"],
    style: "luxury",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 210,
    useCount: 112,
  },
  {
    slug: "confetti-pop",
    name: "Confetti Pop",
    category: "birthday",
    shortDescription: "Bright confetti for any age.",
    description:
      "Loud, cheerful, and deliberately unsubtle. Scales from a child's party to a fortieth without changing character.",
    designer: "ML Printing Studio",
    tags: ["confetti", "colourful", "party", "fun"],
    colors: ["coral", "yellow"],
    styles: ["playful", "modern"],
    features: ["rsvp", "gallery"],
    style: "kids",
    orientation: "SQUARE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 8,
    useCount: 122,
  },
  {
    slug: "first-year",
    name: "First Year",
    category: "birthday",
    shortDescription: "A first birthday, gently done.",
    description:
      "Built around one large photograph and a short message. Intended for first birthdays, where the picture is the invitation and the text is the caption.",
    designer: "Isla Studio",
    tags: ["baby", "first", "milestone", "photo"],
    colors: ["cream", "sky"],
    styles: ["minimal", "soft"],
    features: ["rsvp", "gallery"],
    style: "portrait",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 90,
    useCount: 74,
  },
  {
    slug: "cake-smash",
    name: "Cake Smash",
    category: "birthday",
    shortDescription: "Bunting and balloons for a first birthday.",
    description:
      "Bunting across the head of the card, balloons under it, confetti at the foot. Written for a first birthday held at home, with room for the programme and directions.",
    designer: "ML Printing Studio",
    tags: ["first-birthday", "balloons", "party", "children"],
    colors: ["coral", "cream"],
    styles: ["playful", "soft"],
    features: ["rsvp", "map", "gallery"],
    style: "kids",
    orientation: "SQUARE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 6,
    useCount: 103,
  },
  {
    slug: "golden-sixty",
    name: "Golden Sixty",
    category: "birthday",
    shortDescription: "A sixtieth birthday, formally announced.",
    description:
      "A milestone birthday suite in gold on burgundy, with a panel for the numeral and pages for a tribute programme. Intended for a sixtieth or seventieth held as a dinner.",
    designer: "ML Printing Studio",
    tags: ["milestone", "sixtieth", "foil", "formal"],
    colors: ["burgundy", "gold"],
    styles: ["elegant", "classic"],
    features: ["rsvp", "timeline", "gallery"],
    style: "gold-foil",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 135,
    useCount: 94,
  },
  {
    slug: "seventh-heaven",
    name: "Seventh Heaven",
    category: "birthday",
    shortDescription: "Sparkles and pastels for a seventh birthday.",
    description:
      "A fairy-tale birthday suite with a crescent of light over the name. Built for the Filipino seventh birthday, where the guest list is long and the theme is the point.",
    designer: "Isla Studio",
    tags: ["fairy", "seventh", "sparkle", "children"],
    colors: ["blush", "sky"],
    styles: ["playful", "soft"],
    features: ["rsvp", "gallery", "map"],
    style: "fairy",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 27,
    useCount: 57,
  },
  {
    slug: "neon-eighteen",
    name: "Neon Eighteen",
    category: "debut",
    shortDescription: "High-contrast neon for a modern debut.",
    description:
      "A debut suite with neon accents on near-black. Designed screen-first: the website version carries the design, and the printed piece is a deliberately restrained companion.",
    designer: "Isla Studio",
    tags: ["neon", "modern", "bold", "debut"],
    colors: ["magenta", "black"],
    styles: ["modern", "playful"],
    features: ["rsvp", "gallery", "timeline", "music"],
    style: "luxury",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: false,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 21,
    useCount: 88,
  },
  {
    slug: "eighteen-roses",
    name: "Eighteen Roses",
    category: "debut",
    shortDescription: "The traditional debut, done properly.",
    description:
      "Structured for the Filipino debut: room for the eighteen roses, eighteen candles, and eighteen treasures without the page collapsing into a list.",
    designer: "ML Printing Studio",
    tags: ["traditional", "roses", "candles", "debut"],
    colors: ["burgundy", "gold"],
    styles: ["classic", "elegant"],
    features: ["rsvp", "timeline", "gallery"],
    style: "floral",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 160,
    useCount: 156,
  },
  {
    slug: "cotillion-waltz",
    name: "Cotillion Waltz",
    category: "debut",
    shortDescription: "Debut | Cotillion | Formal",
    description:
      "A debut suite for a programme that runs to a cotillion: a deco fan above the name, then pages for the eighteen roses, the candles, and the order of the dance.",
    designer: "ML Printing Studio",
    tags: ["debut", "cotillion", "formal", "programme"],
    colors: ["navy", "gold"],
    styles: ["elegant", "classic"],
    features: ["rsvp", "timeline", "gallery", "music"],
    style: "luxury",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 41,
    useCount: 118,
  },
  {
    slug: "sagala",
    name: "Sagala",
    category: "debut",
    shortDescription: "Debut | Santacruzan | Soft and ceremonial",
    description:
      "Borrowed from the Santacruzan sagala: an arc of light over the debutante's name, and space for the court of eighteen. Suits a debut held in the afternoon.",
    designer: "Bantayan Press",
    tags: ["sagala", "santacruzan", "filipino", "debut"],
    colors: ["blush", "gold"],
    styles: ["elegant", "soft"],
    features: ["rsvp", "gallery", "timeline"],
    style: "fairy",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 68,
    useCount: 49,
  },
  {
    slug: "blue-hour",
    name: "Blue Hour",
    category: "debut",
    shortDescription: "Portrait-led debut in dusk blues.",
    description:
      "A debut suite built around a single portrait, set in the blues of late afternoon. The name sits above the figure, so a full-length shot is not cropped to fit the frame.",
    designer: "Isla Studio",
    tags: ["portrait", "debut", "photo", "evening"],
    colors: ["navy", "blush"],
    styles: ["modern", "elegant"],
    features: ["rsvp", "gallery", "timeline", "music"],
    style: "portrait",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 15,
    useCount: 72,
  },
  {
    slug: "little-dove",
    name: "Little Dove",
    category: "christening",
    shortDescription: "Quiet, reverent, uncluttered.",
    description:
      "A christening suite with a single dove motif and generous white space. Deliberately plain — the occasion supplies the weight.",
    designer: "Isla Studio",
    tags: ["dove", "baptism", "quiet", "faith"],
    colors: ["ivory", "sky"],
    styles: ["minimal", "classic"],
    features: ["rsvp", "map"],
    style: "minimal",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 75,
    useCount: 52,
  },
  {
    slug: "sacred-olive",
    name: "Sacred Olive",
    category: "christening",
    shortDescription: "Olive branches and warm stone.",
    description:
      "Olive branch illustrations on a warm stone ground. Reads as a keepsake, and is the strongest of the christening suites in print.",
    designer: "Cebu Type Co.",
    tags: ["olive", "baptism", "keepsake", "botanical"],
    colors: ["olive", "stone"],
    styles: ["rustic", "classic"],
    features: ["rsvp", "gallery", "map"],
    style: "floral",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: false,
    isFeatured: false,
    publishedDaysAgo: 300,
    useCount: 39,
  },
  {
    slug: "sunday-best",
    name: "Sunday Best",
    category: "christening",
    shortDescription: "An illustrated child for a baptism.",
    description:
      "A christening invitation with an illustrated child at the centre and the service details set below. Drawn, so families who have not had a photo session can still send it early.",
    designer: "Isla Studio",
    tags: ["baptism", "illustrated", "child", "church"],
    colors: ["sky", "cream"],
    styles: ["soft", "classic"],
    features: ["rsvp", "map", "gallery"],
    style: "portrait",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 23,
    useCount: 44,
  },
  {
    slug: "little-bloom",
    name: "Little Bloom",
    category: "baby-shower",
    shortDescription: "Soft florals for a baby shower.",
    description:
      "A baby shower invitation in soft florals, with room for a gift registry note and directions. Gender-neutral by design — nothing in the palette assumes an answer.",
    designer: "ML Printing Studio",
    tags: ["baby-shower", "floral", "soft", "neutral"],
    colors: ["blush", "sage"],
    styles: ["elegant", "playful"],
    features: ["rsvp", "map", "gallery"],
    style: "floral",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 21,
    useCount: 33,
  },
  {
    slug: "sweet-pea",
    name: "Sweet Pea",
    category: "baby-shower",
    shortDescription: "Playful pastels and hand lettering.",
    description:
      "A brighter baby shower suite with hand-lettered headings and pastel blocks. Made for a shower that leans fun rather than formal.",
    designer: "Bantayan Press",
    tags: ["baby-shower", "pastel", "playful", "lettering"],
    colors: ["seafoam", "cream"],
    styles: ["playful", "modern"],
    features: ["rsvp", "map"],
    style: "kids",
    orientation: "SQUARE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 63,
    useCount: 27,
  },
  {
    slug: "sweet-dreams",
    name: "Sweet Dreams",
    category: "baby-shower",
    shortDescription: "Stars and soft light for a baby shower.",
    description:
      "A night-sky baby shower suite with scattered light above the name. Quiet enough for a small shower at home, and carries a registry note and a map.",
    designer: "Bantayan Press",
    tags: ["stars", "baby-shower", "night", "soft"],
    colors: ["sky", "ivory"],
    styles: ["soft", "minimal"],
    features: ["rsvp", "map"],
    style: "fairy",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 110,
    useCount: 21,
  },
  {
    slug: "golden-jubilee",
    name: "Golden Jubilee",
    category: "anniversary",
    shortDescription: "Fifty years, stated plainly.",
    description:
      "A golden anniversary suite that resists the urge to decorate. A large numeral, a short line of text, and room for one photograph.",
    designer: "ML Printing Studio",
    tags: ["anniversary", "golden", "milestone", "fifty"],
    colors: ["gold", "ivory"],
    styles: ["classic", "elegant"],
    features: ["rsvp", "gallery", "timeline"],
    style: "gold-foil",
    orientation: "LANDSCAPE",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 240,
    useCount: 67,
  },
  {
    slug: "paper-anniversary",
    name: "Paper Anniversary",
    category: "anniversary",
    shortDescription: "Understated, for the early years.",
    description:
      "Kraft-toned and typographic. Intended for first and second anniversaries, where a modest card suits the occasion better than a suite.",
    designer: "Cebu Type Co.",
    tags: ["kraft", "typographic", "modest", "anniversary"],
    colors: ["kraft", "charcoal"],
    styles: ["minimal", "rustic"],
    features: ["rsvp"],
    style: "minimal",
    orientation: "SQUARE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 30,
    useCount: 28,
  },
  {
    slug: "still-us",
    name: "Still Us",
    category: "anniversary",
    shortDescription: "Two figures for a long marriage.",
    description:
      "An anniversary card with the couple drawn side by side and the year set above them. Made for a twenty-fifth or a fortieth marked with a family dinner rather than a party.",
    designer: "ML Printing Studio",
    tags: ["anniversary", "couple", "illustrated", "milestone"],
    colors: ["sage", "cream"],
    styles: ["soft", "classic"],
    features: ["rsvp", "gallery", "timeline"],
    style: "portrait",
    orientation: "SQUARE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 82,
    useCount: 35,
  },
  {
    slug: "toga-and-tassel",
    name: "Toga and Tassel",
    category: "graduation",
    shortDescription: "Straightforward graduation announcement.",
    description:
      "A graduation announcement built around the photograph and the achievement. Navy and white, with room for the school seal.",
    designer: "Isla Studio",
    tags: ["graduation", "school", "achievement", "photo"],
    colors: ["navy", "white"],
    styles: ["classic", "modern"],
    features: ["gallery", "timeline"],
    style: "portrait",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 55,
    useCount: 45,
  },
  {
    slug: "summa-minimal",
    name: "Summa Minimal",
    category: "graduation",
    shortDescription: "Type only. No ornament.",
    description:
      "A typographic graduation piece with no imagery at all. The cheapest to print and the fastest to fill in.",
    designer: "Cebu Type Co.",
    tags: ["typographic", "minimal", "graduation", "modern"],
    colors: ["black", "white"],
    styles: ["minimal", "modern"],
    features: ["rsvp"],
    style: "minimal",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 5,
    useCount: 19,
  },
  {
    slug: "sablay",
    name: "Sablay",
    category: "graduation",
    shortDescription: "Graduation portrait with room for the sablay.",
    description:
      "A graduation announcement built around the graduate in cap and sash, with the school, the degree, and the date set beneath. Sized as a photo card for relatives abroad.",
    designer: "Cebu Type Co.",
    tags: ["graduation", "sablay", "filipino", "portrait"],
    colors: ["olive", "cream"],
    styles: ["classic", "modern"],
    features: ["gallery", "timeline", "map"],
    style: "portrait",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 11,
    useCount: 63,
  },
  {
    slug: "quarterly-gala",
    name: "Quarterly Gala",
    category: "corporate",
    shortDescription: "Formal corporate evening.",
    description:
      "A corporate gala suite with space for sponsor marks and a programme. Restrained enough to carry a company logo without fighting it.",
    designer: "ML Printing Studio",
    tags: ["corporate", "gala", "formal", "sponsors"],
    colors: ["charcoal", "gold"],
    styles: ["elegant", "modern"],
    features: ["rsvp", "timeline", "map"],
    style: "luxury",
    orientation: "LANDSCAPE",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 180,
    useCount: 71,
  },
  {
    slug: "product-launch",
    name: "Product Launch",
    category: "corporate",
    shortDescription: "Screen-first launch announcement.",
    description:
      "Built for a launch event: a landing page with an RSVP and a countdown, plus a simple printed companion card for the room.",
    designer: "Isla Studio",
    tags: ["launch", "corporate", "modern", "tech"],
    colors: ["indigo", "white"],
    styles: ["modern", "minimal"],
    features: ["rsvp", "map", "countdown"],
    style: "minimal",
    orientation: "LANDSCAPE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 12,
    useCount: 33,
  },
  {
    slug: "boardroom-black",
    name: "Boardroom Black",
    category: "corporate",
    shortDescription: "Corporate | Awards night | Black tie",
    description:
      "A dark corporate suite for an awards night or a company anniversary dinner, with a deco fan above the title and a strip for sponsor marks. Print-only: the layout is a programme, not a page.",
    designer: "ML Printing Studio",
    tags: ["corporate", "awards", "black-tie", "programme"],
    colors: ["black", "gold"],
    styles: ["elegant", "modern"],
    features: ["rsvp", "timeline", "map"],
    style: "luxury",
    orientation: "LANDSCAPE",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: false,
    isFeatured: false,
    publishedDaysAgo: 265,
    useCount: 86,
  },
  {
    slug: "noche-buena",
    name: "Noche Buena",
    category: "family",
    shortDescription: "Christmas gathering, warm and red.",
    description:
      "A Christmas invitation for family gatherings, with parol-inspired geometry and a deep red ground.",
    designer: "ML Printing Studio",
    tags: ["christmas", "parol", "family", "festive"],
    colors: ["red", "gold"],
    styles: ["classic", "playful"],
    features: ["rsvp", "gallery"],
    style: "gold-foil",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 60,
    useCount: 41,
    collections: ["christmas"],
  },
  {
    slug: "handaan-sa-bahay",
    name: "Handaan sa Bahay",
    category: "family",
    shortDescription: "Warm invite for a family gathering at home.",
    description:
      "For the gatherings that do not have a formal name — a homecoming, a thanksgiving, a Sunday everyone is finally free. Room for a programme and directions to the house.",
    designer: "ML Printing Studio",
    tags: ["family", "handaan", "gathering", "warm"],
    colors: ["kraft", "olive"],
    styles: ["rustic", "classic"],
    features: ["rsvp", "map", "gallery", "timeline"],
    style: "portrait",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 40,
    useCount: 22,
  },
  {
    slug: "bahay-kubo",
    name: "Bahay Kubo",
    category: "family",
    shortDescription: "A garden wreath for a family homecoming.",
    description:
      "A leafy ring around the family name, borrowed from the vegetables in the song. For a homecoming or a despedida held in someone's yard, with a programme and a map.",
    designer: "Bantayan Press",
    tags: ["bahay-kubo", "family", "garden", "filipino"],
    colors: ["sage", "kraft"],
    styles: ["rustic", "playful"],
    features: ["rsvp", "map", "gallery"],
    style: "floral",
    orientation: "SQUARE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 97,
    useCount: 29,
  },
  {
    slug: "fiesta-banderitas",
    name: "Fiesta Banderitas",
    category: "fiesta",
    shortDescription: "Banderitas and bright colour.",
    description:
      "A fiesta invitation built on banderitas bunting. Loud on purpose, and the most Cebuano thing in the catalogue.",
    designer: "Cebu Type Co.",
    tags: ["fiesta", "banderitas", "festive", "colourful"],
    colors: ["coral", "yellow"],
    styles: ["playful", "rustic"],
    features: ["rsvp", "map", "gallery"],
    style: "kids",
    orientation: "SQUARE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 100,
    useCount: 58,
    collections: ["summer"],
  },
  {
    slug: "santo-patron",
    name: "Santo Patrón",
    category: "fiesta",
    shortDescription: "Town fiesta programme and novena schedule.",
    description:
      "Built for a barangay or town fiesta: space for the novena schedule, the procession route, and the programme, with a banner motif that survives being printed on newsprint.",
    designer: "Bantayan Press",
    tags: ["fiesta", "patron", "novena", "procession"],
    colors: ["red", "gold"],
    styles: ["festive", "classic"],
    features: ["timeline", "map", "gallery"],
    style: "gold-foil",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 70,
    useCount: 31,
  },
  {
    slug: "reunion-table",
    name: "Reunion Table",
    category: "reunion",
    shortDescription: "Family reunion, long tables.",
    description:
      "A reunion invitation with room for a family tree and a programme. Built around the long table everyone ends up at, with space for the years in between.",
    designer: "Isla Studio",
    tags: ["reunion", "family", "gathering", "programme"],
    colors: ["sage", "kraft"],
    styles: ["rustic", "classic"],
    features: ["rsvp", "gallery", "map", "timeline"],
    style: "classic",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 150,
    useCount: 24,
  },
  {
    slug: "class-of-then",
    name: "Class of Then",
    category: "reunion",
    shortDescription: "Class reunion with a then-and-now gallery.",
    description:
      "A class reunion invitation designed around a then-and-now gallery, with a programme and a table for batch representatives. Warm without tipping into nostalgia-kitsch.",
    designer: "Isla Studio",
    tags: ["reunion", "class", "gallery", "programme"],
    colors: ["navy", "gold"],
    styles: ["classic", "modern"],
    features: ["rsvp", "gallery", "timeline", "map"],
    style: "gold-foil",
    orientation: "LANDSCAPE",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 88,
    useCount: 16,
  },
  {
    slug: "sealed-with-yes",
    name: "Sealed with Yes",
    category: "engagement",
    shortDescription: "Wax-seal engagement announcement.",
    description:
      "An engagement announcement built around a single wax seal and a great deal of white space. Says one thing loudly and nothing else, which is what an announcement is for.",
    designer: "ML Printing Studio",
    tags: ["engagement", "announcement", "modern", "minimal"],
    colors: ["blush", "gold"],
    styles: ["elegant", "modern"],
    features: ["rsvp", "gallery", "map"],
    style: "classic",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: true,
    publishedDaysAgo: 14,
    useCount: 41,
  },
  {
    slug: "long-engagement",
    name: "The Long Engagement",
    category: "engagement",
    shortDescription: "Photo-led engagement party suite.",
    description:
      "A photo-first engagement party invitation. The cover gives the picture the whole page and keeps the type to a single line, so the couple is the design.",
    designer: "Isla Studio",
    tags: ["engagement", "party", "photo", "romantic"],
    colors: ["cream", "sage"],
    styles: ["modern", "minimalist"],
    features: ["rsvp", "gallery", "map", "timeline"],
    style: "portrait",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 46,
    useCount: 19,
  },
  {
    slug: "paper-lanterns",
    name: "Paper Lanterns",
    category: "engagement",
    shortDescription: "Lantern light for an evening engagement party.",
    description:
      "Points of lantern light scattered over a warm ground, for an engagement party held outdoors after dark. Room for the proposal story and directions to the venue.",
    designer: "Cebu Type Co.",
    tags: ["lanterns", "engagement", "evening", "outdoor"],
    colors: ["cream", "gold"],
    styles: ["soft", "modern"],
    features: ["rsvp", "gallery", "map"],
    style: "fairy",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 51,
    useCount: 37,
  },
  {
    slug: "salamat-sa-biyaya",
    name: "Salamat sa Biyaya",
    category: "religious",
    shortDescription: "Thanksgiving mass and blessing.",
    description:
      "A restrained invitation for a thanksgiving mass, house blessing, or church anniversary. Quiet type, a single ornament, and space for the celebrant and the order of service.",
    designer: "ML Printing Studio",
    tags: ["mass", "blessing", "thanksgiving", "church"],
    colors: ["ivory", "olive"],
    styles: ["classic", "elegant"],
    features: ["timeline", "map"],
    style: "minimal",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 52,
    useCount: 18,
  },
  {
    slug: "flores-de-mayo",
    name: "Flores de Mayo",
    category: "religious",
    shortDescription: "Flower offering and procession schedule.",
    description:
      "For the May flower offerings: a ring of blooms around the parish name, with room for the daily schedule and the procession route. Prints legibly on newsprint.",
    designer: "Cebu Type Co.",
    tags: ["flores-de-mayo", "procession", "parish", "filipino"],
    colors: ["blush", "olive"],
    styles: ["classic", "festive"],
    features: ["timeline", "map", "gallery"],
    style: "floral",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 140,
    useCount: 26,
    collections: ["summer"],
  },
  {
    slug: "barangay-assembly",
    name: "Barangay Assembly",
    category: "community",
    shortDescription: "Clear notice for a community programme.",
    description:
      "A community notice built for legibility above all: large date, plain type, and an agenda that reads at a glance on a posted sheet or a phone screen.",
    designer: "Cebu Type Co.",
    tags: ["barangay", "assembly", "notice", "civic"],
    colors: ["navy", "white"],
    styles: ["minimal", "modern"],
    features: ["timeline", "map"],
    style: "classic",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 26,
    useCount: 9,
  },
  {
    slug: "sinulog-street",
    name: "Sinulog Street",
    category: "community",
    shortDescription: "Bunting and confetti for a street programme.",
    description:
      "A barangay notice for a Sinulog street programme: bunting across the head, the schedule underneath, and the route at the foot. Loud enough to be read off a posted sheet.",
    designer: "Bantayan Press",
    tags: ["sinulog", "barangay", "street", "filipino"],
    colors: ["red", "yellow"],
    styles: ["festive", "playful"],
    features: ["timeline", "map", "gallery"],
    style: "kids",
    orientation: "LANDSCAPE",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 73,
    useCount: 14,
  },
  {
    slug: "in-loving-memory",
    name: "In Loving Memory",
    category: "funeral",
    shortDescription: "Quiet memorial notice and service details.",
    description:
      "A memorial notice with the service details, wake schedule, and directions set plainly. Restrained type, generous space, and no ornament that would ask for attention.",
    designer: "ML Printing Studio",
    tags: ["memorial", "funeral", "service", "quiet"],
    colors: ["stone", "white"],
    styles: ["classic", "minimalist"],
    features: ["map", "timeline", "gallery"],
    style: "classic",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 30,
    useCount: 12,
  },
  {
    slug: "eternal-olive",
    name: "Eternal Olive",
    category: "funeral",
    shortDescription: "Olive branch memorial with a tribute page.",
    description:
      "A memorial suite carrying an olive branch and space for a short tribute and photographs. Intended for families who want somewhere for people to gather and remember.",
    designer: "Bantayan Press",
    tags: ["memorial", "funeral", "tribute", "olive"],
    colors: ["olive", "ivory"],
    styles: ["classic", "elegant"],
    features: ["map", "gallery", "timeline"],
    style: "minimal",
    orientation: "PORTRAIT",
    tier: "PREMIUM",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 55,
    useCount: 8,
  },
  {
    slug: "parol-lights",
    name: "Parol Lights",
    category: "custom",
    shortDescription: "Strung lights for anything held in December.",
    description:
      "A general-purpose December invitation with parol lights strung across the top. For the gatherings that are not quite a party and not quite a reunion, and need a card anyway.",
    designer: "ML Printing Studio",
    tags: ["parol", "christmas", "lights", "gathering"],
    colors: ["red", "gold"],
    styles: ["festive", "playful"],
    features: ["rsvp", "map", "gallery"],
    style: "kids",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: true,
    websiteCompatible: true,
    isFeatured: false,
    publishedDaysAgo: 4,
    useCount: 17,
    collections: ["christmas"],
  },
  {
    slug: "draft-preview-only",
    name: "Unreleased Concept",
    category: "custom",
    shortDescription: "Should never appear in the marketplace.",
    description:
      "An unpublished draft. Seeded on purpose: it is the fixture that proves buildWhere's publication check works against a real database, and not only in unit tests.",
    designer: "ML Printing Studio",
    tags: ["draft"],
    colors: ["black"],
    styles: ["minimal"],
    features: [],
    style: "minimal",
    orientation: "PORTRAIT",
    tier: "FREE",
    printCompatible: false,
    websiteCompatible: false,
    isFeatured: false,
    publishedDaysAgo: -1, // Sentinel: never published.
    useCount: 0,
  },
];

/** Colour filter vocabulary — Ph2.md §4 Color Theme. Derived, so it cannot drift from the templates. */
export function seedColors(): string[] {
  return [...new Set(TEMPLATES.flatMap((t) => t.colors))].sort();
}

/** Style filter vocabulary — Ph2.md §4 Style. */
export function seedStyles(): string[] {
  return [...new Set(TEMPLATES.flatMap((t) => t.styles))].sort();
}
